server:
  port: ${PORT:5000}
server:
  address: http://vmmatthes22.informatik.tu-muenchen.de

name: Service-BusinessCoreService

eureka:
  instance.metadataMap:
    appType: core-service

spring:
  cloud:
    stream:
      bindings:
        input: profiles