server:
  port: ${PORT:9000}
server:
  address: http://vmmatthes2.informatik.tu-muenchen.de
name: Zuul proxy
spring:
  cloud:
    stream:
      bindings:
        output: profiles
eureka:
  instance:
    metadataMap:
      appType: gateway-service
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
        isolation:
          strategy: SEMAPHORE
ribbon:
  ReadTimeout: 100000
  ConnectTimeout: 100000